### ISSUE TITLE
Support X-Forwarded-For or X-Real-IP

### ISSUE THREAD

**Issue by aphillipo** [navinpeiris/geoip#3]
So I have my app behind an nginx proxy which means the real IP address is set via headers.

I can do you a quick pull request to %Pug.Conn{} match shortly to add this if said headers exist?

Ta.

**Comment by navinpeiris** [comment]
Thanks for that @aphillipo!

Due to all the different ways of determining actual remote ip depending on your deployment method, and the potential security issues like IP address spoofing, it might be better to get the user to configure this for their application using something like [ajvondrak/remote_ip](https://github.com/ajvondrak/remote_ip) or something else that's more applicable for their environment.

There's also a bit more information [here](https://github.com/elixir-lang/plug/issues/319) on why elixir doesn't do this by default.

The README on this repo should be updated to reflect that information though.

**Comment by aphillipo** [comment]
Ah brilliant!  Thanks for that I'll check it out for sure!
